// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.Infrastructure.Persistence;

#nullable disable

namespace TravelPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TravelPlannerDbContext))]
    [Migration("20260503120001_TurkishSchemaAndCoordinates")]
    partial class TurkishSchemaAndCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HeroDescription")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("Açıklama");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Başlık");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Enlem");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Boylam");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Ad");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Bölge");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("Özet");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Şehirler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeroDescription = "Başlangıç adresinden seçilen yerlere yakınlık ve süreye göre plan oluştur.",
                            HeroTitle = "İstanbul'da seçeceğin durakları mantıklı sıraya koy",
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            Name = "İstanbul",
                            Region = "Marmara",
                            Slug = "istanbul",
                            Summary = "Tarihi yarımada, Boğaz ve semt duraklarıyla yoğun bir şehir rotası."
                        },
                        new
                        {
                            Id = 2,
                            HeroDescription = "Yol üstü molalar ve şehir içi durakları aynı rota planında topla.",
                            HeroTitle = "Edirne için gün gün gezi planı hazırla",
                            Latitude = 41.677100000000003,
                            Longitude = 26.555700000000002,
                            Name = "Edirne",
                            Region = "Marmara",
                            Slug = "edirne",
                            Summary = "Selimiye, tarihi çarşılar ve Meriç hattıyla seçtiğin gün sayısına göre planlanabilen rota."
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Enlem");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Boylam");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Ad");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("İlId");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId", "Name");

                    b.ToTable("İlçeler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 910,
                            Latitude = 37.334809999999997,
                            Longitude = 41.88944,
                            Name = "İdil",
                            ProvinceId = 73
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Locality", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("İlçeId");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Enlem");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Boylam");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Ad");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Name");

                    b.ToTable("YerleşimYerleri", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Enlem");

                    b.Property<int>("LocalityId")
                        .HasColumnType("int")
                        .HasColumnName("YerleşimYeriId");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Boylam");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("Ad");

                    b.HasKey("Id");

                    b.HasIndex("LocalityId", "Name");

                    b.ToTable("Mahalleler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 49054,
                            Latitude = 37.384189999999997,
                            LocalityId = 3964,
                            Longitude = 41.819763000000002,
                            Name = "BEREKETLİ KÖYÜ"
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Kategori");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("ŞehirId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("Açıklama");

                    b.Property<string>("EstimatedVisitDuration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TahminiGeziSüresi");

                    b.Property<int>("EstimatedVisitMinutes")
                        .HasColumnType("int")
                        .HasColumnName("TahminiGeziDakikası");

                    b.Property<bool>("IsOnRouteCandidate")
                        .HasColumnType("bit")
                        .HasColumnName("RotaÜzeriMi");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Enlem");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Boylam");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("Ad");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Name");

                    b.ToTable("GezilecekYerler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tarihi Yer",
                            CityId = 1,
                            Description = "İstanbul'un en ikonik tarihi yapılarından biri.",
                            EstimatedVisitDuration = "1 saat",
                            EstimatedVisitMinutes = 60,
                            IsOnRouteCandidate = false,
                            Latitude = 41.008600000000001,
                            Longitude = 28.9802,
                            Name = "Ayasofya Camii"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Saray",
                            CityId = 1,
                            Description = "Osmanlı saray yaşamını keşfetmek için güçlü bir durak.",
                            EstimatedVisitDuration = "2 saat",
                            EstimatedVisitMinutes = 120,
                            IsOnRouteCandidate = false,
                            Latitude = 41.011499999999998,
                            Longitude = 28.9833,
                            Name = "Topkapı Sarayı"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Manzara",
                            CityId = 1,
                            Description = "Şehir siluetini izlemek için sevilen nokta.",
                            EstimatedVisitDuration = "45 dk",
                            EstimatedVisitMinutes = 45,
                            IsOnRouteCandidate = false,
                            Latitude = 41.025599999999997,
                            Longitude = 28.9741,
                            Name = "Galata Kulesi"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tarihi Yer",
                            CityId = 2,
                            Description = "Mimar Sinan'ın ustalık eseri olarak bilinen merkez durak.",
                            EstimatedVisitDuration = "1 saat",
                            EstimatedVisitMinutes = 60,
                            IsOnRouteCandidate = false,
                            Latitude = 41.678100000000001,
                            Longitude = 26.5594,
                            Name = "Selimiye Camii"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Çarşı",
                            CityId = 2,
                            Description = "Tarihi çarşı ve alışveriş durağı.",
                            EstimatedVisitDuration = "45 dk",
                            EstimatedVisitMinutes = 45,
                            IsOnRouteCandidate = false,
                            Latitude = 41.675600000000003,
                            Longitude = 26.5566,
                            Name = "Ali Paşa Çarşısı"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Manzara",
                            CityId = 2,
                            Description = "Nehir kenarında yürüyüş ve fotoğraf molası.",
                            EstimatedVisitDuration = "30 dk",
                            EstimatedVisitMinutes = 30,
                            IsOnRouteCandidate = false,
                            Latitude = 41.668700000000001,
                            Longitude = 26.543399999999998,
                            Name = "Meriç Köprüsü"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Yol Üstü",
                            CityId = 2,
                            Description = "İstanbul-Edirne yolunda kahve ve sahil molası.",
                            EstimatedVisitDuration = "40 dk",
                            EstimatedVisitMinutes = 40,
                            IsOnRouteCandidate = true,
                            Latitude = 41.073599999999999,
                            Longitude = 28.246400000000001,
                            Name = "Silivri Sahil"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Yol Üstü",
                            CityId = 2,
                            Description = "Yol üstünde kısa yemek ve dinlenme durağı.",
                            EstimatedVisitDuration = "45 dk",
                            EstimatedVisitMinutes = 45,
                            IsOnRouteCandidate = true,
                            Latitude = 41.159100000000002,
                            Longitude = 27.802499999999998,
                            Name = "Çorlu Atalar Meydanı"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Yol Üstü",
                            CityId = 2,
                            Description = "Edirne yolunda tarihi bir mola noktası.",
                            EstimatedVisitDuration = "50 dk",
                            EstimatedVisitMinutes = 50,
                            IsOnRouteCandidate = true,
                            Latitude = 41.406500000000001,
                            Longitude = 27.354900000000001,
                            Name = "Lüleburgaz Sokullu Mehmet Paşa Külliyesi"
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Enlem");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Boylam");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Ad");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("İller", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 73,
                            Latitude = 37.418748100000002,
                            Longitude = 42.491833800000002,
                            Name = "Şırnak"
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.District", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Locality", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.District", "District")
                        .WithMany("Localities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Neighborhood", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.Locality", "Locality")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locality");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Place", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.City", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.District", b =>
                {
                    b.Navigation("Localities");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Locality", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
