// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.Infrastructure.Persistence;

#nullable disable

namespace TravelPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TravelPlannerDbContext))]
    [Migration("20260503105939_InitialTravelPlannerSql")]
    partial class InitialTravelPlannerSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.Domain.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("HeroDescription")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = "istanbul",
                            HeroDescription = "Baslangic adresinden secilen yerlere yakinlik ve sureye gore plan olustur.",
                            HeroTitle = "Istanbul'da sececegin duraklari mantikli siraya koy",
                            Name = "Istanbul",
                            Region = "Marmara",
                            Slug = "istanbul",
                            Summary = "Tarihi yarimada, bogaz ve semt duraklariyla yogun bir sehir rotasi."
                        },
                        new
                        {
                            Id = "edirne",
                            HeroDescription = "Yol ustu molalar ve sehir ici duraklari ayni rota planinda topla.",
                            HeroTitle = "Edirne icin gun gun gezi plani hazirla",
                            Name = "Edirne",
                            Region = "Marmara",
                            Slug = "edirne",
                            Summary = "Selimiye, tarihi carsilar ve Meric hattiyla iki gunluk geziye uygun rota."
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Place", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("EstimatedVisitDuration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EstimatedVisitMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnRouteCandidate")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Name");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = "ayasofya",
                            Category = "Tarihi Yer",
                            CityId = "istanbul",
                            Description = "Istanbul'un en ikonik tarihi yapilarindan biri.",
                            EstimatedVisitDuration = "1 saat",
                            EstimatedVisitMinutes = 60,
                            IsOnRouteCandidate = false,
                            Latitude = 41.008600000000001,
                            Longitude = 28.9802,
                            Name = "Ayasofya Camii"
                        },
                        new
                        {
                            Id = "topkapi",
                            Category = "Saray",
                            CityId = "istanbul",
                            Description = "Osmanli saray yasamini kesfetmek icin guclu bir durak.",
                            EstimatedVisitDuration = "2 saat",
                            EstimatedVisitMinutes = 120,
                            IsOnRouteCandidate = false,
                            Latitude = 41.011499999999998,
                            Longitude = 28.9833,
                            Name = "Topkapi Sarayi"
                        },
                        new
                        {
                            Id = "galata",
                            Category = "Manzara",
                            CityId = "istanbul",
                            Description = "Sehir siluetini izlemek icin sevilen nokta.",
                            EstimatedVisitDuration = "45 dk",
                            EstimatedVisitMinutes = 45,
                            IsOnRouteCandidate = false,
                            Latitude = 41.025599999999997,
                            Longitude = 28.9741,
                            Name = "Galata Kulesi"
                        },
                        new
                        {
                            Id = "selimiye",
                            Category = "Tarihi Yer",
                            CityId = "edirne",
                            Description = "Mimar Sinan'in ustalik eseri olarak bilinen merkez durak.",
                            EstimatedVisitDuration = "1 saat",
                            EstimatedVisitMinutes = 60,
                            IsOnRouteCandidate = false,
                            Latitude = 41.678100000000001,
                            Longitude = 26.5594,
                            Name = "Selimiye Camii"
                        },
                        new
                        {
                            Id = "alic-pasa-carsisi",
                            Category = "Carsi",
                            CityId = "edirne",
                            Description = "Tarihi carsi ve alisveris duragi.",
                            EstimatedVisitDuration = "45 dk",
                            EstimatedVisitMinutes = 45,
                            IsOnRouteCandidate = false,
                            Latitude = 41.675600000000003,
                            Longitude = 26.5566,
                            Name = "Ali Pasa Carsisi"
                        },
                        new
                        {
                            Id = "meric-koprusu",
                            Category = "Manzara",
                            CityId = "edirne",
                            Description = "Nehir kenarinda yuruyus ve fotograf molasi.",
                            EstimatedVisitDuration = "30 dk",
                            EstimatedVisitMinutes = 30,
                            IsOnRouteCandidate = false,
                            Latitude = 41.668700000000001,
                            Longitude = 26.543399999999998,
                            Name = "Meric Koprusu"
                        },
                        new
                        {
                            Id = "silivri-sahil",
                            Category = "Yol Ustu",
                            CityId = "edirne",
                            Description = "Istanbul-Edirne yolunda kahve ve sahil molasi.",
                            EstimatedVisitDuration = "40 dk",
                            EstimatedVisitMinutes = 40,
                            IsOnRouteCandidate = true,
                            Latitude = 41.073599999999999,
                            Longitude = 28.246400000000001,
                            Name = "Silivri Sahil"
                        },
                        new
                        {
                            Id = "corlu-atalar-meydani",
                            Category = "Yol Ustu",
                            CityId = "edirne",
                            Description = "Yol ustunde kisa yemek ve dinlenme duragi.",
                            EstimatedVisitDuration = "45 dk",
                            EstimatedVisitMinutes = 45,
                            IsOnRouteCandidate = true,
                            Latitude = 41.159100000000002,
                            Longitude = 27.802499999999998,
                            Name = "Corlu Atalar Meydani"
                        },
                        new
                        {
                            Id = "luleburgaz-sokullu",
                            Category = "Yol Ustu",
                            CityId = "edirne",
                            Description = "Edirne yolunda tarihi bir mola noktasi.",
                            EstimatedVisitDuration = "50 dk",
                            EstimatedVisitMinutes = 50,
                            IsOnRouteCandidate = true,
                            Latitude = 41.406500000000001,
                            Longitude = 27.354900000000001,
                            Name = "Luleburgaz Sokullu Mehmet Pasa Kulliyesi"
                        });
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.RouteLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("FromTripStopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LegOrder")
                        .HasColumnType("int");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ToTripStopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TrafficDurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripPlanId", "DayNumber", "LegOrder")
                        .IsUnique();

                    b.ToTable("RouteLegs");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedTravelMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedVisitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<DateTime?>("TripDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripPlanId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TripDays");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DestinationCityName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<double?>("DestinationLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("DestinationLongitude")
                        .HasColumnType("float");

                    b.Property<string>("StartAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("TotalTravelMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TransportationMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TravelDays")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("TripPlans");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("DistanceFromPreviousKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedVisitMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnRouteStop")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<TimeSpan?>("PlannedArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("PlannedDepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<int>("TravelMinutesFromPrevious")
                        .HasColumnType("int");

                    b.Property<Guid>("TripDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripDayId", "StopOrder")
                        .IsUnique();

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.Place", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.RouteLeg", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.TripPlan", "TripPlan")
                        .WithMany("RouteLegs")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripDay", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.TripPlan", "TripPlan")
                        .WithMany("Days")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripStop", b =>
                {
                    b.HasOne("TravelPlanner.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelPlanner.Domain.Entities.TripDay", "TripDay")
                        .WithMany("Stops")
                        .HasForeignKey("TripDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("TripDay");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.City", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripDay", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TravelPlanner.Domain.Entities.TripPlan", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("RouteLegs");
                });
#pragma warning restore 612, 618
        }
    }
}
